spring.application.name=study
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# ??? ??? ?? ??
logging.level.org.hibernate.SQL=DEBUG
# ?? ?????
spring.jpa.properties.hibernate.format_sql=true
# ???? ? ????
logging.levle.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# DB URL ??
# ??? URL ???? ??
spring.datasource.generate-unique-name=true
# ?? URL ????
spring.datasource.url=jdbc:h2:mem:testdb
